# Generated by Django 4.1 on 2022-09-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_part', models.CharField(choices=[('Abs', 'Abs'), ('Adductors', 'Adductors'), ('Biceps', 'Biceps'), ('Calves', 'Calves'), ('Chest', 'Chest'), ('Forearms', 'Forearms'), ('Front Delts', 'Front Delts'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings'), ('Hip Flexors', 'Hip Flexors'), ('Lats', 'Lats'), ('Lower Back', 'Lower Back'), ('Obliques', 'Obliques'), ('Quads', 'Quads'), ('Rear Delts', 'Rear Delts'), ('Side Delts', 'Side Delts'), ('Traps', 'Traps'), ('Triceps', 'Triceps')], default='Abs', max_length=40)),
                ('video_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('exercise_info', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['body_part'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='fitness.WorkoutExercise', to='fitness.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('training_notes', models.CharField(max_length=10000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ManyToManyField(to='fitness.workout')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_in_cms', models.CharField(max_length=5)),
                ('weight_in_kgs', models.CharField(max_length=5)),
                ('fitness_goal', models.CharField(choices=[('Fat Loss', 'Fat Loss'), ('Gain Muscle', 'Gain Muscle'), ('Gain Strength', 'Gain Strength')], default='Fat Loss', max_length=20)),
                ('previous_exercise_experience', models.CharField(choices=[('Zero Experience', 'Zero Experience'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Zero Experience', max_length=20)),
                ('current_activity_level', models.CharField(choices=[('No Activity', 'No Activity'), ('Light Activity', 'Light Activity'), ('Moderate Activity', 'Moderate Activity'), ('Intense Activity', 'Intense Activity')], default='No Activity', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('desired_timeframe', models.CharField(max_length=100, null=True)),
                ('any_injuries_or_underlying_health_conditions', models.TextField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
